### ISSUE TITLE
Links to sections on page are jarring

### ISSUE THREAD

**Issue by SheepTester** [Objay1003/te-amo-website#5]
I can understand if this is for accessibility reasons, but if not, you can use [`scroll-behavior: smooth;`](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior) to have a nice transition to the destination section

**Comment by Objay1003** [comment]
Where would I have this in my css

**Comment by SheepTester** [comment]
the `<style>` tag

**Comment by SheepTester** [comment]
Added in https://github.com/Objay1003/te-amo-website/commit/21e4c68d664066e758d1235598a58ba574d72141
